config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
  end
  resources :contacts
  get '/about' => 'pages#about'
  root 'pages#home'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
  attr_accessor :stripe_card_token
  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation) }
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
  	  @contact = Contact.new
  end

	def create
	  @contact = Contact.new(contact_params)
	  if @contact.save
	    name = params[:contact][:name]
	    email = params[:contact][:email]
	    body = params[:contact][:comments]
	    ContactMailer.contact_email(name, email, body).deliver
	    flash[:success] = 'Message sent.'
	    redirect_to new_contact_path
	  else
	    flash[:danger] = 'Error occured, message has not been sent.'
	    redirect_to new_contact_path
	  end
	end

  private
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
      @basic_plan = Plan.find(1)
      @full_plan = Plan.find(2)
    end
    def about
    	@basic_plan = Plan.find(1)
    	@full_plan = Plan.find(2)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :only_current_user
  def new
    # form where a user can fill out their own profile.
    @user = User.find( params[:user_id] )
    @profile = Profile.new
  end
  def create 
    @user = User.find( params[:user_id] )
    @profile = @user.build_profile(profile_params)
    if @profile.save
      flash[:success] = "Profile Updated!"
      redirect_to user_path( params[:user_id] )
    else
      render action: :new
    end
  end
  def edit
    @user = User.find( params[:user_id] )
    @profile = @user.profile
  end
  def update
    @user = User.find( params[:user_id] )
    @profile = @user.profile
    if @profile.update_attributes(profile_params)
      flash[:success] = "Profile Updated!"
      redirect_to user_path( params[:user_id] )
    else
      render action: :edit
    end
  end
  private
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title, :phone_number, :contact_email, :description)
    end
    def only_current_user
      @user = User.find( params[:user_id] )
      redirect_to(root_url) unless @user == current_user
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_filter :select_plan, only: :new

  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_payment
        else
          resource.save
        end
      end
    end
  end

  private
  def select_plan
    unless params[:plan] && (params[:plan] == '1' || params[:plan] == '2')
      flash[:notice] = "Please select a membership plan to sign up."
      redirect_to root_url
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find( params[:id] )
  end
  def index
    @users = User.includes(:profile)
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <p>#{sentence}</p>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="wellhead-main">
        <h4>Contact Us</h4>
      </div>
    <div class="well">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <p>Reach out if you have any questions or comments.</p>
          <%= form_for @contact do |f| %>
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :email %>
              <%= f.email_field :email, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :comments %>
              <%= f.text_area :comments, class: 'form-control' %>
            </div>
            <%= f.submit 'Submit', class: 'btn btn-default btn-lg btn-block' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dogparc</title>
  <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Quicksand:700|Work+Sans:400,700,300',media: 'all' %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
  <%= javascript_include_tag 'application' %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
  <!-- Favicon info -->
  <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
  <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
  <link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
  <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
  <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
  <link rel="manifest" href="/manifest.json">
  <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="msapplication-TileImage" content="/mstile-144x144.png">
  <meta name="theme-color" content="#ffffff">
</head>

<body>

<div id="wrap">

<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <i class="fa fa-paw"></i>
        Dogparc
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <div class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary navbar-btn' %>
        <% else %>
          <%= link_to "Log In", new_user_session_path, class: 'btn btn-primary navbar-btn', method: :get %>
        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Community", users_path %></li>
          <li><%= link_to "My Account", edit_user_registration_path %></li>
        <% end %>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", new_contact_path %></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container" id="main">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "alert alert-#{key}" %>
  <% end %>
  <%= yield %>
</div>

</div>

<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <p class="social">
        <a class="btn btn-social-icon btn-facebook">
          <i class="fa fa-facebook"></i>
        </a>
        <a class="btn btn-social-icon btn-twitter">
          <i class="fa fa-twitter"></i>
        </a>
        <a class="btn btn-social-icon btn-google">
          <i class="fa fa-google"></i>
        </a>
      </p>
      </div>
      <div class="col-sm-4">
        <ul class="foot">
          <li><%= link_to "About Us", about_path %></li>
           <li><%= link_to "Contact Us", new_contact_path %></li>
           <li><%= link_to "My Account", edit_user_registration_path %></li>
        </ul>
      </div>
      <div class="col-sm-4">
        <ul class="foot">
          <li><a href="#">Privacy Policy</a> </li>
          <li><a href="#">Terms of Service</a> </li>
          <li><a href="#">Career Opportunities</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

</body>

</html>

app/views/pages/about.html.erb
<div class="row">
	<div class="col-xs-12">

		<div class="col-xs-12" id="about">
			<h2>Dogparc is a Denver-based service that connects canine professionals to potential clients.</h2>
		</div>

		<div class="well" >
			<div class="row">

				<div class="col-sm-6 pull-left" id="aboutdesc">
					<p>Denver is a city famous for dog-lovers. Because of that, we know just how many services our beloved pooches need: And that's why Dogparc exists. From dog trainers, to walkers, to sitters, to new clients for your canine business, you can find anything you're looking for, all within your city. Have a question not covered on this page? <%= link_to "Get in touch.", new_contact_path %></p>
				</div>

				<div class="col-sm-6 pull-right" id="aboutimg">
					<img class="img-responsive" src="/assets/doggie.jpg" />
					<p class="caption">Joey's family found him a great sitter here on Dogparc.</p>
				</div>

				<div class="col-sm-6 pull-left" id="aboutdesc">
					<h4>What is a Full Account?</h4>
						<p>A basic account only allows you to preview the names and job titles of our registered users. However, a full account enables you to see full contact information. This allows users to see professional contact information, and also allows professionals to see user contact information to solicit their services.
						</p>
						<%= link_to "Sign up today!", new_user_registration_path(plan: @full_plan.id), class: 'btn btn-default btn-lg btn-block' %>
				</div>

			</div>
		</div>

	</div>
</div>

app/views/pages/home.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="/assets/sitting.jpg" alt="dogsitters" />
      <div class="carousel-caption">
        <h4>Find the perfect sitter to stay with your furry friend while you're away.</h4>
      </div>
    </div>

    <div class="item">
      <img src="/assets/training.jpg" alt="obedience trainers" />
      <div class="carousel-caption">
        <h4>Join today to browse through our database of trusted canine obedience trainers.</h4>
      </div>
    </div>

    <div class="item">
      <img src="/assets/walking.jpg" alt="dog walkers" />
      <div class="carousel-caption">
        <h4>A new dogwalker for your pal is just a few clicks away.</h4>
      </div>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class="row">
  <% if user_signed_in? %>
    <div class="col-md-6">
      <div class="wellhead">
          <h2 class="text-center">Your Profile</h2>
        </div>

      <div class="well" id="signed-in">
        <%if current_user.plan_id == 2 %>
          <% if current_user.profile %>
            <%= link_to "Edit your profile", edit_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
            <%= link_to "View your profile", user_path(current_user), class: 'btn btn-default btn-lg btn-block' %>
          <% else %>
            <p>Create your profile so that you can share your information with the community.</p>
            <%= link_to "Create your profile", new_user_profile_path(current_user), class: 'btn btn-default btn-lg btn-block'%>
          <% end %><% end %>
        <% if current_user.plan_id == 1 %>
          <p>You have a basic account, which is limited. In order to make a profile and gain access to all our users' contact information, you need to sign up instead for a full account.</p>
          <p>Full accounts cost only $3/month to use!</p>
          <%end%>
        
      </div>
    </div>
    <div class="col-md-6">
      <div class="wellhead">
          <h2 class="text-center">The Community</h2>
        </div>
      <div class="well" id="signed-in">
        <p>Visit The Community to see a full directory of canine professionals in your area!</p>
        <%= link_to "Visit the community", users_path, class: 'btn btn-default btn-lg btn-block' %>
      </div>
    </div>
  <% else %>
    <div class="col-sm-6">
      <div class="wellhead">
        <h2 class="text-center">Basic Membership</h2>
      </div>
      <div class="well" id="signed-out">
        <p>Sign up for free and get a sneak-peek at our community's local Dogparc users.</p>
        <%= link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-default btn-lg btn-block' %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="wellhead">
        <h2 class="text-center">Full Membership</h2>
      </div>
      <div class="well" id="signed-out">
        <p>Sign up for a Full Account for $3/month and get access to users' contact info!</p>
        <%= link_to "Sign up with Full", new_user_registration_path(plan: @full_plan.id), class: 'btn btn-default btn-lg btn-block' %>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :job_title %>
    <%= f.select :job_title, ['Dogparc User', 'Trainer', 'Walker', 'Sitter', 'Other'], {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :contact_email %>
    <%= f.text_field :contact_email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-default btn-lg btn-block' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="wellhead-main">
        <h4>Edit Your Profile</h4>
      </div>
    <div class="well">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="well">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <h1 class="text-center">Create Your Profile</h1>
          <p class="text-center">Be a part of the Dogparc community and fill out your profile!</p>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="wellhead-main">
        <h4>Dogparc Community</h4>
      </div>
    <div class="well" id="intro">
    
    <p>In order to be listed, users must have a full account, fill out a profile, and be local to Denver.</p>
    
    <ul class="list-unstyled">
      <% @users.each do |user| %>
        <% if user.profile %>

        <li>

          <div class="well" id="user">

            <div class="col-sm-3">
              <% if user.profile.avatar %>
                <%= link_to user do %>
                    <%= image_tag user.profile.avatar.url(:thumb), class: 'user-index-avatar' %>
                  <% end %>
                <% end %>
              </div>

            <div>
              <%= link_to user do %>
                <h2><%= user.profile.first_name %> <%= user.profile.last_name %></h2>
              <% end %>
              <p>
                <%= user.profile.job_title %> 
              </p>
            </div>

          </div>

        </li>

        <% end %>
      <% end %>
    </ul>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="wellhead-main">
        <h4>Dogparc Community</h4>
      </div>
    <div class="well">

      <div class="row">
        
        <div class="col-sm-3">
          <div class="profimg"><%= image_tag @user.profile.avatar.url %></div>
        </div>

        <div class="col-sm-9" id="proftop">
          <h1><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>
          <h3>
              <%= @user.profile.job_title %><br/>
          </h3>
      
          <% if current_user.plan_id == 2 %>
            <h4><%= @user.profile.phone_number %><br/></h4>
            <h4><%= @user.profile.contact_email %><br/></h4>
          <% end %>
        </div>

        <div class="col-sm-9 col-sm-offset-3">
          <div class="well" id="profdesc">
            <%= @user.profile.description %>
          </div>
        </div>
    
      </div>

    </div>
  </div>
</div>